### ISSUE TITLE
sha1 painless produces incorrect values for UTF-8 encoded text

### ISSUE THREAD

**Issue by JeffBolle** [sektorcap/sha-painless#1]
In the sha1.painless file the sha is incorrect for byte arrays involving some characters. I encountered it when attempting to do a hash on a string involving this character: 🔥

Because bytes in Painless are signed, you need to properly convert it to an unsigned int. In line 6, you should do `(x[i] & 255)`.

So all of line 6 should be:

```
			blks[i >> 2] |= (x[i] & 255) << (24 - (i % 4) * 8);

```
The code as it it will work for ascii (because the byte value == the int value under 127), but for utf-8 characters, painless would produced a signed byte, where it should be unsigned when converted into an int.

**Comment by sektorcap** [comment]
Thanks for your contribution
